FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential pkg-config bison flex

COPY . /Brainfuck
WORKDIR /Brainfuck
RUN make

FROM ubuntu:20.04 as package
COPY --from=builder /Brainfuck/bin/bf2lua /
